### PR TITLE
Better `modified` detection

### PR DESCRIPTION
**Pull request by deforestg**
recursively convert `dict`s into `CallbackDict`s to better detect when values are changed

### CODE REVIEW

**Comment by deforestg** [comment]
decided against this

**Comment by fengsp** [comment]
@deforestg Why? Performance?

**Comment by deforestg** [comment]
because I realized that it inherently modifies the data that is being stored in the session if it is a dict - so for instance if you have a line that says `if type(session['thing']) is dict:` then that will no longer work since its been converted to a `CallbackDict` instead

**Comment by fengsp** [comment]
@deforestg And it doesn't apply to other mutable objects like `list`, so `modified` detection is still a problem.  Try to keep it simple, just do this:

    data = session['key']
    # modify data here
    session['key'] = data

**Pull request closed without merging**
