### PR TITLE
If signing goes wrong, instead of failing with 'str + None' error

### PR DESCRIPTION
**Pull request by victorgp**
Just return an invalid session.

### CODE REVIEW

**Comment by fengsp** [comment]
Fixed

**Comment by victorgp** [comment]
Mmm... what do you mean with Fixed? i don't see any new commit and my pull request is not merged

**Comment by fengsp** [comment]
@victorgp Just release 0.2.1, give it a try :)

**Comment by victorgp** [comment]
Ok, got it! i'll give it a try, thanks!

**Comment by victorgp** [comment]
@fengsp works like a charm!! Thank you!

**Pull request closed without merging**
